name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        architecture: [x64, arm64]
        include:
          - os: macos-latest
            architecture: x64
            target: mac
          - os: macos-latest
            architecture: arm64
            target: mac-arm
          - os: windows-latest
            architecture: x64
            target: win

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run build

      - name: Package Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          package_root: ./
          build_command: npm run dist
          args: --publish never
          mac_target: ${{ matrix.target }}
          windows_target: nsis

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-app-${{ matrix.os }}-${{ matrix.architecture }}
          path: dist/*
