# .github/workflows/release.yml
name: Release app
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        architecture: [x64, arm64]
        exclude:
          - os: windows-latest
            architecture: arm64
        include:
          - os: macos-latest
            architecture: x64
            target: mac
          - os: macos-latest
            architecture: arm64
            target: mac-arm
          - os: windows-latest
            architecture: x64
            target: win
    runs-on: ${{ matrix.os }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: npm i
      - if: matrix.os == 'macos-latest'
        run: npm install -g appdmg
      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish
